config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'questions/show'
  get 'questions/result'
  get 'questions/search'
  get 'questions/beforeresult', as: 'beforeresult'


  get 'profile/show', to: "users#show"
  get 'profile/edit', to: "users#edit"

  root to: 'pages#home'
  resources :pages
  resources :categories, only: [:index, :show]
  resources :quiz do
    resources :quiz_sessions, only: [:create]
  end
  resources :quiz_sessions, except: :create do
    get 'last_question', to: 'last_questions#show'
    resources :user_answers, only: :create
    resources :questions, only: [:show] do
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :sub_categories, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @categories = Category.all
    @electronics = Category.where(name: "Electronics")
    @outdoors = Category.where(name: "Outdoors")
    @electronics_sub_categories = SubCategory.where(category: @electronics)
    @outdoors_sub_categories = SubCategory.where(category: @outdoors)
  end

  def search
    if params[:query].present?
      @sub_category = Sub_category.where(name: params[:query])
    else
      @sub_category = Sub_category.all
    end
  end

  def show
    @category = Category.find(params[:id])
    @sub_categories = SubCategory.where(params[:category_id])
    # @sub_category = SubCategory.find(params[:id])
  end
end

app/views/categories/index.html.erb
<div class="navbar-fixed-top searchbar">

  <div class="searchterm">
    <div class="search-block">
      <i class="fas fa-search"> </i>
      <%= form_tag  questions_search_path, method: :get, class: "aa-input-container", id: "aa-input-container" do %>
      <%= text_field_tag :query, params[:query], placeholder: "Which product do you need?", class: "header-for", id: "query-input", class: "aa-input-search" %>
    <% end %>
    </div>
  </div>
</div>

<div class="container-with-search">
<h4>Hi, Yash. Which category do you want to explore?</h4>
  <div id="carousel-1" class="carousel">
   <% @categories.each do |category| %>
     <div class="carousel-item">
      <div class="card">
        <div class="card__image">
          <%= link_to category_path(category) do %>
          <%= cl_image_tag category.photo, height: 250, width:250, crop: :fill %>
          <% end %>
        </div>
        <div class="card__info">
          <h2 class="card__title"><%= category.name %></h2>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h5>Recommended Outdoors</h5>
  <div id="carousel-3" class="carousel">
   <% @outdoors_sub_categories.each do |sub_category| %>
     <div class="carousel-item">
      <div class="card">
        <div class="card__image">
          <%= link_to '#', method: :post do %>
          <%= cl_image_tag sub_category.photo, height: 250, width:250, crop: :fill %>
          <% end %>
        </div>
        <div class="card__info">
          <h2 class="card__title"><%= sub_category.name %></h2>
        </div>
      </div>
    </div>
  <% end %>
</div>

<h5>Recommended Electronics</h5>
  <div id="carousel-2" class="carousel">
   <% @electronics_sub_categories.each do |sub_category| %>
     <div class="carousel-item">
      <div class="card">
        <div class="card__image">
          <%= link_to quiz_quiz_sessions_path(sub_category.quiz), method: :post do %>
          <%= cl_image_tag sub_category.photo, height: 250, width:250, crop: :fill %>
          <% end %>
        </div>
        <div class="card__info">
          <h2 class="card__title"><%= sub_category.name %></h2>
        </div>
      </div>
    </div>
  <% end %>
</div>


</div>


<%= javascript_include_tag 'https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js' %>
<%= javascript_pack_tag 'autocomplete' %>

app/views/categories/show.html.erb
<div class="navbar-fixed-top searchbar">

  <div class="searchterm">
    <div class="search-block">
      <i class="fas fa-search"> </i>
      <%= form_tag  questions_search_path, method: :get, class: "aa-input-container", id: "aa-input-container" do %>
      <%= text_field_tag :query, params[:query], placeholder: "Which product do you need?", class: "header-form", id: "query-input", class: "aa-input-search" %>
    <% end %>
    </div>
  </div>
</div>


<div class="container-with-search-2">

<div class="container">
  <h4>Recommended <%= @category.name %></h4>
  <div class="no-gutter categories-container">
    <% @sub_categories.each do |sub_category| %>
      <% if sub_category.quiz %>

         <div class="carousel-item">
            <div class="card">
              <div class="card__image">
                <%= link_to quiz_quiz_sessions_path(sub_category.quiz), method: :post, class: "card-image-container" do %>
                <%= cl_image_tag sub_category.photo, crop: :fill%>
                <% end %>
              </div>
              <div class="card__info">
                <h2 class="card__title"><%= sub_category.name %></h2>
              </div>
            </div>
          </div>

      <% end %>
    <% end %>
  </div>
</div>
</div>